/**
 * Helpers for the generated embed modules that `bun build --compile` bakes
 * into the release binary (scripts/build-compile.ts). Kept apart from the build
 * script so the stub restore and the simulator viewer manifest are unit-tested
 * without compiling anything.
 */

import {
  mkdirSync,
  readdirSync,
  readFileSync,
  statSync,
  writeFileSync,
} from "fs";
import { dirname, join, relative, resolve } from "path";

export const GENERATED_MODULE_HEADER = [
  "// AUTO-GENERATED by scripts/build-compile.ts for `bun build --compile`.",
  "// Do not edit or commit: the build restores the src stub afterwards.",
  "/* eslint-disable */",
];

/**
 * Import specifier for `path` relative to the directory of `fromModule`. The
 * embed modules live deep under packages/ while the built assets sit elsewhere,
 * so the module's own directory anchors every specifier and its depth never has
 * to be tracked by hand.
 */
export function embedSpecifier(fromModule: string, path: string): string {
  const spec = relative(dirname(fromModule), resolve(path)).replaceAll(
    "\\",
    "/",
  );
  return spec.startsWith(".") ? spec : `./${spec}`;
}

/**
 * Write the served simulator viewer assets into `distDir`, one file per served
 * path. The `/` shell is a string constant in assets.ts and is not written:
 * Bun bundles a `.html` import as an entry point rather than embedding it.
 */
export async function writeSimulatorViewerDist(
  files: ReadonlyMap<string, Blob>,
  distDir: string,
): Promise<string[]> {
  mkdirSync(distDir, { recursive: true });
  const written: string[] = [];
  for (const [served, blob] of files) {
    if (served === "/") continue;
    const name = served.slice(1);
    if (!served.startsWith("/") || !name || name.includes("/"))
      throw new Error(`unexpected simulator viewer asset path ${served}`);
    await Bun.write(join(distDir, name), blob);
    written.push(name);
  }
  return written.sort();
}

/**
 * Source for `src/simulator-portal/embedded-viewer.ts` at release time: one
 * `import … with { type: "file" }` per built viewer asset in `distDir`, and a
 * manifest mapping the served path back to the embedded file.
 */
export function generateSimulatorViewerEmbedModule(
  distDir: string,
  modulePath: string,
): string {
  const names = readdirSync(distDir)
    .filter(
      (name) => !name.startsWith(".") && statSync(join(distDir, name)).isFile(),
    )
    .sort();
  for (const required of ["main.js", "main.css", "utilities.css"])
    if (!names.includes(required))
      throw new Error(`simulator viewer build produced no ${required}`);
  const lines = [...GENERATED_MODULE_HEADER];
  const entries: string[] = [];
  names.forEach((name, index) => {
    const ident = `__v${index}`;
    lines.push(
      `import ${ident} from ${JSON.stringify(embedSpecifier(modulePath, join(distDir, name)))} with { type: "file" };`,
    );
    entries.push(`\t\t${JSON.stringify(`/${name}`)}: ${ident},`);
  });
  lines.push(
    "",
    "export const EMBEDDED_SIMULATOR_VIEWER = {",
    "\tassets: {",
    ...entries,
    "\t},",
    "};",
    "",
  );
  return lines.join("\n");
}

/**
 * Overwrite each stub module with its generated content for the duration of
 * `run`, then restore every stub, also when `run` throws, so the working tree
 * never keeps a generated module (which would leak the build machine's asset
 * paths into a commit and break the source install).
 */
export async function withGeneratedModules<T>(
  modules: ReadonlyArray<{ path: string; content: string }>,
  run: () => Promise<T>,
): Promise<T> {
  const stubs = modules.map(({ path }) => ({
    path,
    stub: readFileSync(path, "utf8"),
  }));
  try {
    for (const { path, content } of modules) writeFileSync(path, content);
    return await run();
  } finally {
    for (const { path, stub } of stubs) writeFileSync(path, stub);
  }
}
