#!/usr/bin/env bun
/**
 * Generate the capability catalogs under docs/generated/:
 *
 *   docs/generated/mcp-tools.md  — every in-process MCP tool, with its server,
 *                                  input summary and gating.
 *   docs/generated/engines.md    — the engine adapters, their config gates, and
 *                                  which models route to which engine.
 *
 * Run it after changing an in-process MCP server, the wiring that hands one to
 * a run, the engine adapters, or the model registry:
 *
 *     bun scripts/gen-catalogs.ts
 *
 * scripts/gen-catalogs.test.ts regenerates both files into a temp dir and fails
 * when the committed copies differ, so a stale catalog is a red test rather
 * than a doc nobody trusts.
 *
 * How the tool data is obtained: every server in MCP_SERVER_CATALOG
 * (packages/core/opensession-server/src/server/mcp-catalog.ts) is BUILT — the same call the runtime makes — and
 * asked for tools/list over an in-memory MCP transport. Wiring tests compare
 * the catalog with the interactive and automation server sets so additions to
 * those runtime surfaces cannot be omitted here.
 *
 * Determinism: tool descriptions interpolate instance config (the persona name,
 * the default repo's label, the list owner's timezone), so the whole generator
 * runs against a HERMETIC config + state dir written to a temp directory. The
 * output is therefore identical on every checkout and in CI, and describes the
 * shipped defaults rather than whichever instance ran it. Server modules are
 * imported dynamically, AFTER that environment is in place.
 */

import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from "fs";
import { tmpdir } from "os";
import { join, resolve } from "path";

const REPO_ROOT = resolve(import.meta.dir, "..");
const GENERATED_BY = "scripts/gen-catalogs.ts";

/** Instance config the catalog is rendered against — fixed, so the generated
 *  files never carry one machine's repo names, persona or paths. */
const FIXTURE_CONFIG = {
  repos: {
    example: {
      repo: "/srv/example",
      label: "example",
      ghRepo: "example/repo",
      defaultBranch: "main",
      default: true,
    },
  },
};

// ── Rendering helpers ────────────────────────────────────────────────────────

function header(title: string, blurb: string): string {
  return [
    `<!-- Generated by ${GENERATED_BY}. Do not edit by hand.`,
    `     Regenerate with: bun ${GENERATED_BY} -->`,
    "",
    `# ${title}`,
    "",
    blurb,
    "",
  ].join("\n");
}

/** A JSON Schema property rendered as `name (type, required)`. */
function inputSummary(schema: unknown): string {
  const s = schema as
    | { properties?: Record<string, any>; required?: string[] }
    | undefined;
  const props = s?.properties;
  if (!props || !Object.keys(props).length) return "none";
  const required = new Set(s?.required || []);
  return Object.entries(props)
    .map(
      ([name, spec]) =>
        `\`${name}\` (${schemaType(spec)}${required.has(name) ? ", required" : ""})`,
    )
    .join(", ");
}

function schemaType(spec: any): string {
  if (!spec || typeof spec !== "object") return "any";
  if (Array.isArray(spec.enum))
    return spec.enum.map((v: unknown) => JSON.stringify(v)).join(" | ");
  if (spec.type === "array") return `${schemaType(spec.items)}[]`;
  if (Array.isArray(spec.anyOf)) return spec.anyOf.map(schemaType).join(" | ");
  if (typeof spec.type === "string") return spec.type;
  if (spec.properties) return "object";
  return "any";
}

/** Collapse a tool description onto one paragraph — descriptions are prompts,
 *  and their line breaks are incidental. */
function oneParagraph(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

// ── mcp-tools.md ─────────────────────────────────────────────────────────────

interface ListedTool {
  name: string;
  description: string;
  inputSchema: unknown;
}

async function listTools(server: { instance: unknown }): Promise<ListedTool[]> {
  const { Client } = await import("@modelcontextprotocol/sdk/client/index.js");
  const { InMemoryTransport } =
    await import("@modelcontextprotocol/sdk/inMemory.js");
  const [clientTransport, serverTransport] =
    InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "gen-catalogs", version: "1.0.0" });
  await (server.instance as any).connect(serverTransport);
  await client.connect(clientTransport);
  try {
    const res = await client.listTools();
    return (res.tools || []).map((t: any) => ({
      name: t.name,
      description: t.description || "",
      inputSchema: t.inputSchema,
    }));
  } finally {
    await client.close().catch(() => {});
  }
}

const RUN_CLASS_LABEL: Record<string, string> = {
  interactive: "interactive",
  automation: "automation",
  slack: "Slack loop",
  goal: "goal wake",
  unwired: "**unwired**",
};

async function renderMcpTools(): Promise<string> {
  const { MCP_SERVER_CATALOG } = await import(
    `${REPO_ROOT}/packages/core/opensession-server/src/server/mcp-catalog.ts`
  );
  const { AUTOMATION_DENIED_TOOLS } = await import(
    `${REPO_ROOT}/packages/core/opensession-server/src/server/automation-denied-tools.ts`
  );
  const { STRIPE_CONFIRM_TOOLS } = await import(
    `${REPO_ROOT}/packages/core/opensession-server/src/server/runner-shared.ts`
  );

  const out: string[] = [
    header(
      "In-process MCP tools",
      [
        "Every tool Open Session serves from inside its own process — the",
        "`opensession-*` servers — with the gating that decides which runs can",
        "call it. Tool names and inputs are read from the live server objects",
        "(`tools/list`), so this file cannot drift from the code; the run classes",
        "and conditions are declared in `packages/core/opensession-server/src/server/mcp-catalog.ts` beside each",
        "entry and checked against the interactive and automation wiring by `mcp-catalog.test.ts`.",
        "",
        "External MCP servers (`mcp-config.json`) are NOT listed here: they are",
        "per-instance configuration, and their per-user `allowedUsers` scoping is",
        "enforced in `filterMcpServers` (`packages/core/opensession-server/src/server/runner-shared.ts`).",
        "",
        "**How gating works.** An in-process server reaches a run only if a call",
        "site hands it over, so the *run class* column is the real permission",
        "boundary:",
        "",
        "- **interactive** — the web UI and native clients, via",
        "  `interactiveMcpServers()` (`packages/core/opensession-server/src/server/interactive-mcp.ts`).",
        "- **automation** — unattended runs on untrusted text. They receive only",
        "  the servers `automations.ts` builds for them; the run-rpc fallback",
        "  resolver fails closed for automation-owned sessions, so asking for an",
        "  interactive server yields nothing.",
        "- **Slack loop**, **goal wake** — their own narrow sets.",
        "",
        "Additional external-tool filters apply selectively; neither currently",
        "touches an in-process tool:",
        "",
        "- `AUTOMATION_DENIED_TOOLS` (`packages/core/opensession-server/src/server/automation-denied-tools.ts`) —",
        "  stripped from automation runs and from interactive resumes of",
        "  automation-owned sessions.",
        "- `STRIPE_CONFIRM_TOOLS` (`packages/core/opensession-server/src/server/runner-shared.ts`) — money movers,",
        "  stripped on standard run paths. The Plain integration's separately",
        "  classified explicit-approval path deliberately runs without this filter.",
      ].join("\n"),
    ),
  ];

  // Summary table.
  out.push("## Servers", "");
  out.push("| Server | Tools | Runs | Condition |");
  out.push("| --- | --- | --- | --- |");
  const built: Array<{
    entry: any;
    tools: ListedTool[];
    variants: Array<{
      label: string;
      tools: ListedTool[];
      runClasses: string[];
    }>;
  }> = [];
  for (const entry of MCP_SERVER_CATALOG) {
    const tools = await listTools(entry.build());
    const variants: Array<{
      label: string;
      tools: ListedTool[];
      runClasses: string[];
    }> = [];
    for (const v of entry.variants || []) {
      variants.push({
        label: v.label,
        tools: await listTools(v.build()),
        runClasses: v.runClasses,
      });
    }
    built.push({ entry, tools, variants });
    out.push(
      `| [\`${entry.name}\`](#${entry.name}) | ${tools.length} | ${entry.runClasses
        .map((r: string) => RUN_CLASS_LABEL[r] || r)
        .join(", ")} | ${
        entry.condition ? entry.condition.replace(/\|/g, "\\|") : "–"
      } |`,
    );
  }
  const total = built.reduce((n, b) => n + b.tools.length, 0);
  out.push("", `${built.length} servers, ${total} tools.`, "");

  for (const { entry, tools, variants } of built) {
    out.push(`## ${entry.name}`, "", entry.summary, "");
    out.push(`- **Source** \`${entry.source}\``);
    out.push(
      `- **Wired in** ${
        entry.wiring.length
          ? entry.wiring.map((w: string) => `\`${w}\``).join(", ")
          : "nowhere"
      }`,
    );
    out.push(
      `- **Runs** ${entry.runClasses.map((r: string) => RUN_CLASS_LABEL[r] || r).join(", ")}`,
    );
    if (entry.condition) out.push(`- **Condition** ${entry.condition}`);
    if (entry.note) out.push(`- **Note** ${entry.note}`);
    const denied = tools
      .map((t) => `mcp__${entry.name}__${t.name}`)
      .filter(
        (id) => id in AUTOMATION_DENIED_TOOLS || id in STRIPE_CONFIRM_TOOLS,
      );
    if (denied.length) {
      out.push(
        `- **Stripped from unattended runs** ${denied.map((d) => `\`${d}\``).join(", ")}`,
      );
    }
    out.push("");
    for (const t of tools) {
      out.push(`### \`${t.name}\``, "");
      out.push(
        `\`mcp__${entry.name}__${t.name}\` · input: ${inputSummary(t.inputSchema)}`,
        "",
      );
      if (t.description) out.push(oneParagraph(t.description), "");
    }
    for (const v of variants) {
      const names = new Set(tools.map((t) => t.name));
      const extra = v.tools
        .filter((t) => !names.has(t.name))
        .map((t) => t.name);
      const missing = tools
        .filter((t) => !v.tools.some((x) => x.name === t.name))
        .map((t) => t.name);
      out.push(
        `### Variant · ${v.label}`,
        "",
        `Built for: ${v.runClasses.map((r: string) => RUN_CLASS_LABEL[r] || r).join(", ")}. ` +
          `${v.tools.length} tools` +
          (missing.length
            ? `, without ${missing.map((m) => `\`${m}\``).join(", ")}`
            : "") +
          (extra.length
            ? `, plus ${extra.map((m) => `\`${m}\``).join(", ")}`
            : "") +
          ".",
        "",
      );
    }
  }
  return (
    out
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}

// ── engines.md ───────────────────────────────────────────────────────────────

/** Prose for each engine id. The SET is driven by ENGINE_IDS (plus the test
 *  seam), and mcp-catalog.test.ts fails when an id has no entry here — so a
 *  new engine cannot ship without a line in the catalog. */
export const ENGINE_NOTES: Record<
  string,
  { title: string; adapter: string; prefix: string; gate: string; note: string }
> = {
  pi: {
    title: "pi",
    adapter: "packages/core/opensession-server/src/server/pi-runner.ts",
    prefix: "`pi/<provider>/<model>`",
    gate: "`enabled` in `piConfigPath()` (normally `~/.opensession/pi.json`; an existing legacy `~/.opensession-pi.json` is still honored). A missing config disables Pi, while first-run onboarding creates it enabled.",
    note:
      "In-process engine. `pi/anthropic/*` turns reach the Claude Agent SDK through the native " +
      'in-process provider by default (`anthropicTransport`, `"bridge"` for the loopback rollback).',
  },
  fake: {
    title: "fake (tests only)",
    adapter:
      "packages/core/opensession-server/src/server/agent-runner.ts — the __setEngineForTest seam; fixture implementation in packages/core/opensession-server/src/server/testing/fake-engine.ts; coverage in packages/core/opensession-server/src/server/fake-engine.test.ts",
    prefix: "– (intercepts every model id)",
    gate:
      "Not config-gated and not reachable in production: it is a module-local test seam, set only " +
      "by a test and cleared by any hot reload.",
    note:
      "Checked FIRST in `runOnModel`, before engine routing, so a fake intercepts every engine's " +
      "turns. It also owns its own model availability unless a test installs the separate probe.",
  },
};

async function renderEngines(): Promise<string> {
  const models = await import(
    `${REPO_ROOT}/packages/core/opensession-server/src/server/models.ts`
  );
  const ENGINE_IDS = ["pi"] as const;
  // Read the ids from the engine registry so a new one cannot be missed, but
  // lead with the default engine rather than the union's alphabetical order.
  const lead = ["pi"];
  const ids: string[] = [
    ...lead.filter((id) => (ENGINE_IDS as readonly string[]).includes(id)),
    ...[...ENGINE_IDS].filter((id: string) => !lead.includes(id)).sort(),
    "fake",
  ];

  const out: string[] = [
    header(
      "Engines",
      [
        "Which engine runs a turn, what turns it on, and where each model lands.",
        "The routing table below is computed by calling `routeModel()`",
        "(`packages/core/opensession-server/src/server/models.ts`) in the generator's",
        "hermetic clean state. Pi is the only production engine, so routing is unconditional.",
        "",
        "`routeModel()` sends every accepted model and preset to Pi.",
        "Native ids and provider/model paths normalize to `pi/<provider>/<model>`.",
      ].join("\n"),
    ),
  ];

  out.push("## Adapters", "");
  for (const id of ids) {
    const e = ENGINE_NOTES[id];
    if (!e) continue;
    out.push(`### ${e.title} · \`${id}\``, "");
    out.push(`- **Adapter** \`${e.adapter}\``);
    out.push(`- **Model ids** ${e.prefix}`);
    out.push(`- **Gate** ${e.gate}`);
    out.push(`- **Mid-turn steer** ${steerLabel(models, id)}`);
    out.push(`- **Note** ${e.note}`, "");
  }

  out.push(
    "## Model routing",
    "",
    "Every id in `KNOWN_MODELS`, plus the Dial and Orchestrator presets, with the",
    "engine and dispatch id `routeModel()` returns for it.",
    "",
    "| Model id | Label | Engine | Dispatched as |",
    "| --- | --- | --- | --- |",
  );
  const rows: Array<{ id: string; label: string }> = [
    ...models.KNOWN_MODELS.map((m: any) => ({ id: m.id, label: m.label })),
    ...models.DIAL_PRESETS.map((p: any) => ({ id: p.id, label: p.label })),
    ...models.ORCHESTRATOR_PRESETS.map((p: any) => ({
      id: p.id,
      label: p.label,
    })),
  ];
  for (const row of rows) {
    const route = models.routeModel(row.id);
    out.push(
      `| \`${row.id}\` | ${row.label} | ${route.engine} | \`${route.model}\` |`,
    );
  }
  out.push(
    "",
    "Every accepted id resolves to Pi before dispatch.",
    "",
    "| Example id | Routes to |",
    "| --- | --- |",
  );
  for (const example of [
    "pi/anthropic/claude-opus-5",
    "anthropic/claude-opus-5",
    "openai/gpt-5.6-sol",
  ]) {
    const route = models.routeModel(example);
    out.push(`| \`${example}\` | ${route.engine} |`);
  }
  out.push("");
  return (
    out
      .join("\n")
      .replace(/\n{3,}/g, "\n\n")
      .trimEnd() + "\n"
  );
}

function steerLabel(models: any, id: string): string {
  if (id === "fake") return "n/a";
  const probe: Record<string, string> = {
    pi: "pi/anthropic/claude-opus-5",
  };
  return models.modelSupportsSteer(probe[id]) ? "yes" : "no";
}

// ── Entry point ──────────────────────────────────────────────────────────────

/** Render both catalogs. Callers must have the hermetic env in place already
 *  (see main) — this is exported for the test, which runs the CLI instead. */
export async function renderCatalogs(): Promise<Record<string, string>> {
  return {
    "mcp-tools.md": await renderMcpTools(),
    "engines.md": await renderEngines(),
  };
}

async function main() {
  const args = process.argv.slice(2);
  const outIdx = args.indexOf("--out");
  const outDir =
    outIdx >= 0
      ? resolve(args[outIdx + 1]!)
      : join(REPO_ROOT, "docs/generated");

  // Hermetic config + state, so the catalog describes the shipped defaults and
  // is byte-identical everywhere. Set BEFORE the first server-module import.
  const sandbox = mkdtempSync(join(tmpdir(), "gen-catalogs-"));
  writeFileSync(
    join(sandbox, "config.json"),
    JSON.stringify(FIXTURE_CONFIG, null, 2),
  );
  writeFileSync(
    join(sandbox, "mcp-config.json"),
    JSON.stringify({ mcpServers: {} }, null, 2),
  );
  process.env.OPENSESSION_CONFIG = join(sandbox, "config.json");
  process.env.OPENSESSION_MCP_CONFIG = join(sandbox, "mcp-config.json");
  process.env.OPENSESSION_STATE_DIR = sandbox;
  process.env.OPENSESSION_SESSIONS_DIR = join(sandbox, "sessions");
  mkdirSync(join(sandbox, "sessions"), { recursive: true });

  try {
    const files = await renderCatalogs();
    mkdirSync(outDir, { recursive: true });
    for (const [name, content] of Object.entries(files)) {
      writeFileSync(join(outDir, name), content);
      console.log(
        `${join(outDir, name)} — ${content.split("\n").length} lines`,
      );
    }
  } finally {
    rmSync(sandbox, { recursive: true, force: true });
  }
}

if (import.meta.main) {
  await main();
}
